config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'items/index'
 
  get 'home/search' => 'home#search'
  get 'home/search' => 'home#keyword'
  get 'home/toparea' => 'home#show'

  post "users/:id/update" => "users#update"
  get "users/:id/edit" => "users#edit"
  post "users/create" => "users#create"
  get "signup" => "users#new"
  get "users/index" => "users#index"
  get "users/:id" => "users#show"

  get "posts/index" => "posts#index"
  get "posts/new" => "posts#new"
  post "posts/new" => "posts#new"
  get "posts/:id" => "posts#show"
  post "posts/create" => "posts#create"
  get "posts/:id/edit" => "posts#edit"
  post "posts/:id/update" => "posts#update"
  post "posts/:id/destroy" => "posts#destroy"

  get "items/new/:id" => "items#new"
  post "items/create" => "items#create"
  get "items/:id/show" => "items#show"
  get "items/:id/edit" => "items#edit"
  post "items/:id/update" => "items#update"
  post "items/:id/destroy" => "items#destroy"

  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'


  get "/" => "home#index"

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users
  resources :posts
  resources :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  belongs_to :post, optional: true

  def self.search(search)
    if search
      Item.where(['product_name LIKE ? OR brand LIKE ?', "%#{search}%", "%#{search}%"])
    else
      Item.all
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @posts = Post.all
    @user = current_user
    @items = @user.items
    # @userの子であるitemに限定する
  end

  def new
    @post = Post.find_by(id: params[:id])
    @item = Item.new(item_image: params[:item_image],
                     brand: params[:brand],
                     size: params[:size],
                     price: params[:price],
                     products_name: params[:products_name],
                     post_id: params[:post_id])
  end

  def create
    @item = Item.new(item_image: params[:item_image],
                     brand: params[:brand],
                     size: params[:size],
                     price: params[:price],
                     products_name: params[:products_name],
                     post_id: params[:post_id])
    @item.user_id = current_user.id
    if @item.save
      @item.item_image = "#{@item.id}.jpg"
      image = params[:item_image]
      File.binwrite("app/assets/images/items/#{@item.item_image}", image.read)
      redirect_to("/items/#{@item.post_id}/show")
    else
      render('/items/new')
    end
  end

  def show
    @item = Item.find_by(params[:id])
    @post = Post.find_by(id: params[:id])
    @items = @post.items
  end

  def edit
    @item = Item.find_by(params[:id])
  end

  def update
    @item = Item.find_by(params[:id])
    @item.products_name = params[:products_name]
    @item.brand = params[:brand]
    @item.size = params[:size]
    @item.price = params[:price]
    @item.item_image = "#{@item.id}.jpg"
    image = params[:item_image]
    File.binwrite("app/assets/images/items/#{@item.item_image}", image.read)
    if @item.save
      redirect_to("/posts/#{@item.post.id}")
    else
      render("items/#{@item.post.id}/edit")
    end
  end

  def destroy
    @item = Item.find_by(params[:post_id])
    @item.destroy
    redirect_to("/posts/#{@item.post.id}")
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<div class="main posts-new">
  <div class="container">
    <h1 class="form-heading">編集する</h1>
 <td><%= @item.post.id %></td>

    <%= form_tag("/items/#{@item.post.id}/update", multipart: true ) do %>
      <div class="form">
        <div class="form-body">
          <table class="msr_text_05">
        <tr>
          <th><span class="must">必須</span><%= "アイテム写真" %></th>
          <td><input type="file" name="item_image" value="<%= @item.item_image %>"></td>
        </tr>
        <tr>
          <th><span class="must">必須</span><%= "アイテム名" %></th>
          <td><input name="products_name" value="<%= @item.products_name %>"></td>
        </tr>
        <tr>
          <th><span class="must">必須</span><%= "ブランド" %></th>
          <td><input name="brand" value="<%= @item.brand %>"></td>
        </tr>
        <tr>
          <th><span class="must">必須</span><%= "サイズ" %></th>
          <td><input name="size" value="<%= @item.size %>"></td>
        </tr>
        <tr>
          <th><span class="must">必須</span><%= "価格" %></th>
          <td><span>&yen;</span><input name="price" value="<%= @item.price %>"></td>

          <input id="item.post.id" name="item.post.id"  value="<%= @item.post.id %>">

        </tr>
      </table>
          <input type="submit" value="保存">
        </div>
      </div>
    <% end %>

  </div>
</div>

app/views/items/index.html.erb
<h1>Items#index</h1>
<p>Find me in app/views/items/index.html.erb</p>

app/views/items/new.html.erb
<div class="main posts-new">
  <div class="container">
    <h1 class="form-heading">アイテム登録画面</h1>

    <%= form_tag("/items/create", {multipart: true})do %>
      <div class="form">
        <div class="form-body">
          <table class="msr_text_05">
            <tr>
              <th><%= "アイテム写真" %></th>
              <td><input type="file" name="item_image" value="<%= @item.item_image %>"></td>
            </tr>
            <tr>
              <th><%= "アイテム名" %></th>
              <td><input name="products_name" value="<%= @item.products_name %>"></td>
            </tr>
            <tr>
              <th><%= "ブランド" %></th>
              <td><input name="brand" value="<%= @item.brand %>"></td>
            </tr>
            <tr>
              <th><%= "サイズ" %></th>
              <td><input name="size" value="<%= @item.size %>"></td>
            </tr>
            <tr>
              <th><%= "価格" %></th>
              <td><span>&yen;</span><input name="price" value="<%= @item.price %>"></td>
            </tr>
            <input type="hidden" id="post_id" name="post_id"  value="<%= @post.id %>">
          </table>

          <div>
            <ul >
              <input class="btn btn-primary" type="submit" value="登録" >
            </ul>
          </div>

        </div>
      </div>
    <% end %>
    <br>
    <%= link_to("トップページへ戻る", "/") %>
  </div>
</div>

app/views/items/show.html.erb
<div class="main posts-show">
  <div class="container">
    <div class="posts-show-item">

    <% @items.each do |item| %>
        <tr>
          <% if File.exist?("app/assets/images/items/#{item.id}.jpg") %>
              <td><%= image_tag "items/#{item.id}" %></td>
            <% else %>
              <td><%= image_tag "noimage.png" %></td>
            <% end %>
      <tr>
        <!--アイテム画像-->
        <td></td>
      </tr>
      <tr>
        <!--アイテム名-->
        <td><%= item.products_name %></td>
      </tr>
      <tr>
        <!--ブランド-->
        <td><%= item.brand %></td>
      </tr>
      <tr>
        <!--サイズ-->
        <td><%= item.size %></td>
      </tr>
      <tr>
        <!--価格-->
        <td><%= item.price %></td>
      </tr>
    <% end %>



      <div class="post-time">
        <%= @item.created_at.strftime("%Y-%m-%d") %>
      </div>
      <% if @post.user_id == @current_user.id %>
              <div class="postmenus">
                <%= link_to("アイテム編集", edit_item_path) %>
                <%= link_to("アイテム削除", "/items/#{@item.post.id}/destroy", method: "post") %>
              </div>
            <% end %>
      <%= link_to("コーディネート画面へ戻る", "/posts/#{@post.id}") %>
    </div>
  </div>
  <%= link_to("トップページへ", "/") %>
</div>